"""fix uuid4 default for refresh tokens

Revision ID: e40e9c1fe10a
Revises: 5aafa74ba77b
Create Date: 2026-09-02 00:02:14.497417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40e9c1fe10a'
down_revision: Union[str, Sequence[str], None] = '5aafa74ba77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
